AllCops:
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Enabled: true
  Max: 120
Style/FrozenStringLiteralComment:
  Description: 'Ruby 3.0 transition for frozen string literals'
  Enabled: false
Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Documentation:
  Exclude:
    - 'spec/**/*.rb'
