defaults: &defaults
  working_directory: ~/repo

  steps:
    - checkout

    - restore_cache:
        keys:
          - gem-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
          - gem-cache-{{ .Branch }}
          - gem-cache

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        key: gem-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

    - run:
        name: run rubocop
        command: bundle exec rubocop

    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          bundle exec rspec --format progress \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress

    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

version: 2
jobs:
  build-ruby-2.5.0:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.0

  build-ruby-2.4.3:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.3

  build-ruby-2.3.6:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.3.6

  build-ruby-2.2.9:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.2.9

workflows:
  version: 2
  build:
    jobs:
      - build-ruby-2.5.0
      - build-ruby-2.4.3
      - build-ruby-2.3.6
      - build-ruby-2.2.9
